# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\hp\Desktop\inż\myPlug2\gui_alfa3.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(671, 661)
        Form.setLayoutDirection(QtCore.Qt.LeftToRight)
        Form.setStyleSheet("background-color: rgb(44, 44, 44);")
        self.title = QtWidgets.QLabel(Form)
        self.title.setGeometry(QtCore.QRect(230, 10, 251, 51))
        self.title.setStyleSheet("font: 75 16pt \"Myanmar Text\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.title.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.title.setLineWidth(1)
        self.title.setMidLineWidth(0)
        self.title.setObjectName("title")
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(20, 280, 291, 21))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(Form)
        self.line_2.setGeometry(QtCore.QRect(20, 440, 281, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.step3 = QtWidgets.QLabel(Form)
        self.step3.setGeometry(QtCore.QRect(70, 470, 211, 16))
        self.step3.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 11pt \"MS Shell Dlg 2\";")
        self.step3.setObjectName("step3")
        self.browse_button1 = QtWidgets.QPushButton(Form)
        self.browse_button1.setGeometry(QtCore.QRect(10, 130, 51, 51))
        self.browse_button1.setStyleSheet("background-color: rgb(13, 101, 195);\n"
"color: rgb(255, 255, 255)")
        self.browse_button1.setIconSize(QtCore.QSize(33, 33))
        self.browse_button1.setObjectName("browse_button1")
        self.step2 = QtWidgets.QLabel(Form)
        self.step2.setGeometry(QtCore.QRect(80, 300, 221, 18))
        self.step2.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 11pt \"MS Shell Dlg 2\";")
        self.step2.setObjectName("step2")
        self.step6 = QtWidgets.QLabel(Form)
        self.step6.setGeometry(QtCore.QRect(410, 470, 221, 18))
        self.step6.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 11pt \"MS Shell Dlg 2\";")
        self.step6.setObjectName("step6")
        self.line_3 = QtWidgets.QFrame(Form)
        self.line_3.setGeometry(QtCore.QRect(370, 440, 281, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(20, 340, 281, 61))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.box_step3_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.box_step3_2.setContentsMargins(0, 0, 0, 0)
        self.box_step3_2.setObjectName("box_step3_2")
        self.label_fname1 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_fname1.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 7pt \"MS Shell Dlg 2\";\n"
"")
        self.label_fname1.setObjectName("label_fname1")
        self.box_step3_2.addWidget(self.label_fname1)
        self.input_fname1 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.input_fname1.sizePolicy().hasHeightForWidth())
        self.input_fname1.setSizePolicy(sizePolicy)
        self.input_fname1.setStyleSheet("background-color: rgb(208, 208, 208);")
        self.input_fname1.setText("")
        self.input_fname1.setObjectName("input_fname1")
        self.box_step3_2.addWidget(self.input_fname1)
        self.save_file1 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save_file1.sizePolicy().hasHeightForWidth())
        self.save_file1.setSizePolicy(sizePolicy)
        self.save_file1.setStyleSheet("background-color: rgb(13, 101, 195);\n"
"color: rgb(255, 255, 255);")
        self.save_file1.setObjectName("save_file1")
        self.box_step3_2.addWidget(self.save_file1)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(360, 140, 281, 31))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.box_step4_1 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.box_step4_1.setContentsMargins(0, 0, 0, 0)
        self.box_step4_1.setObjectName("box_step4_1")
        self.label_radius1 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_radius1.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 7pt \"MS Shell Dlg 2\";\n"
"")
        self.label_radius1.setObjectName("label_radius1")
        self.box_step4_1.addWidget(self.label_radius1)
        self.radius1 = QtWidgets.QDoubleSpinBox(self.horizontalLayoutWidget_3)
        self.radius1.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radius1.sizePolicy().hasHeightForWidth())
        self.radius1.setSizePolicy(sizePolicy)
        self.radius1.setMouseTracking(True)
        self.radius1.setAcceptDrops(True)
        self.radius1.setStyleSheet("background-color: rgb(208, 208, 208);\n"
"selection-color: rgb(90, 181, 249);")
        self.radius1.setAccelerated(True)
        self.radius1.setProperty("value", 3.0)
        self.radius1.setObjectName("radius1")
        self.box_step4_1.addWidget(self.radius1)
        self.ok1 = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.ok1.setStyleSheet("background-color: rgb(13, 101, 195);\n"
"color: rgb(255, 255, 255);")
        self.ok1.setObjectName("ok1")
        self.box_step4_1.addWidget(self.ok1)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(360, 500, 281, 31))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.box_step6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.box_step6.setContentsMargins(0, 0, 0, 0)
        self.box_step6.setObjectName("box_step6")
        self.label_radius2 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_radius2.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 7pt \"MS Shell Dlg 2\";\n"
"")
        self.label_radius2.setObjectName("label_radius2")
        self.box_step6.addWidget(self.label_radius2)
        self.radius2 = QtWidgets.QDoubleSpinBox(self.horizontalLayoutWidget_4)
        self.radius2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radius2.sizePolicy().hasHeightForWidth())
        self.radius2.setSizePolicy(sizePolicy)
        self.radius2.setMouseTracking(True)
        self.radius2.setAcceptDrops(True)
        self.radius2.setStyleSheet("background-color: rgb(208, 208, 208);\n"
"selection-color: rgb(90, 181, 249);")
        self.radius2.setAccelerated(True)
        self.radius2.setProperty("value", 3.0)
        self.radius2.setObjectName("radius2")
        self.box_step6.addWidget(self.radius2)
        self.ok2 = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.ok2.setStyleSheet("background-color: rgb(13, 101, 195);\n"
"color: rgb(255, 255, 255);")
        self.ok2.setObjectName("ok2")
        self.box_step6.addWidget(self.ok2)
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(360, 530, 281, 41))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.box_step6_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.box_step6_2.setContentsMargins(0, 0, 0, 0)
        self.box_step6_2.setObjectName("box_step6_2")
        self.label_fname3 = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        self.label_fname3.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 7pt \"MS Shell Dlg 2\";\n"
"")
        self.label_fname3.setObjectName("label_fname3")
        self.box_step6_2.addWidget(self.label_fname3)
        self.input_fname3 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.input_fname3.sizePolicy().hasHeightForWidth())
        self.input_fname3.setSizePolicy(sizePolicy)
        self.input_fname3.setStyleSheet("background-color: rgb(208, 208, 208);")
        self.input_fname3.setText("")
        self.input_fname3.setObjectName("input_fname3")
        self.box_step6_2.addWidget(self.input_fname3)
        self.save_file3 = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save_file3.sizePolicy().hasHeightForWidth())
        self.save_file3.setSizePolicy(sizePolicy)
        self.save_file3.setStyleSheet("background-color: rgb(13, 101, 195);\n"
"color: rgb(255, 255, 255);")
        self.save_file3.setObjectName("save_file3")
        self.box_step6_2.addWidget(self.save_file3)
        self.button_close = QtWidgets.QPushButton(Form)
        self.button_close.setGeometry(QtCore.QRect(420, 620, 121, 31))
        self.button_close.setStyleSheet("background-color: rgb(13, 101, 195);\n"
"color: rgb(255, 255, 255);")
        self.button_close.setObjectName("button_close")
        self.add_hs = QtWidgets.QPushButton(Form)
        self.add_hs.setGeometry(QtCore.QRect(580, 330, 51, 41))
        self.add_hs.setStyleSheet("background-color: rgb(13, 101, 195);\n"
"color: rgb(255, 255, 255)")
        self.add_hs.setIconSize(QtCore.QSize(33, 30))
        self.add_hs.setObjectName("add_hs")
        self.line_5 = QtWidgets.QFrame(Form)
        self.line_5.setGeometry(QtCore.QRect(30, 590, 611, 20))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.step1 = QtWidgets.QLabel(Form)
        self.step1.setGeometry(QtCore.QRect(100, 70, 219, 21))
        self.step1.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 11pt \"MS Shell Dlg 2\";")
        self.step1.setObjectName("step1")
        self.step4 = QtWidgets.QLabel(Form)
        self.step4.setGeometry(QtCore.QRect(400, 70, 219, 21))
        self.step4.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 11pt \"MS Shell Dlg 2\";")
        self.step4.setObjectName("step4")
        self.line_6 = QtWidgets.QFrame(Form)
        self.line_6.setGeometry(QtCore.QRect(323, 100, 20, 461))
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_7 = QtWidgets.QFrame(Form)
        self.line_7.setGeometry(QtCore.QRect(20, 50, 611, 20))
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.line_8 = QtWidgets.QFrame(Form)
        self.line_8.setGeometry(QtCore.QRect(370, 280, 281, 21))
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.step5 = QtWidgets.QLabel(Form)
        self.step5.setGeometry(QtCore.QRect(410, 300, 221, 18))
        self.step5.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 11pt \"MS Shell Dlg 2\";")
        self.step5.setObjectName("step5")
        self.browser_files1 = QtWidgets.QTextBrowser(Form)
        self.browser_files1.setGeometry(QtCore.QRect(70, 130, 101, 111))
        self.browser_files1.setStyleSheet("background-color: rgb(208, 208, 208);\n"
"selection-color: rgb(118, 197, 230);")
        self.browser_files1.setObjectName("browser_files1")
        self.load1 = QtWidgets.QPushButton(Form)
        self.load1.setGeometry(QtCore.QRect(70, 250, 241, 23))
        self.load1.setStyleSheet("background-color: rgb(13, 101, 195);\n"
"color: rgb(255, 255, 255);")
        self.load1.setObjectName("load1")
        self.browser_files1_2 = QtWidgets.QTextBrowser(Form)
        self.browser_files1_2.setGeometry(QtCore.QRect(210, 130, 101, 111))
        self.browser_files1_2.setStyleSheet("background-color: rgb(208, 208, 208);\n"
"selection-color: rgb(118, 197, 230);")
        self.browser_files1_2.setObjectName("browser_files1_2")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(70, 110, 101, 20))
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 8pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(210, 110, 101, 20))
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 8pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(180, 170, 21, 21))
        self.label_3.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.clear_files1 = QtWidgets.QPushButton(Form)
        self.clear_files1.setGeometry(QtCore.QRect(10, 190, 51, 51))
        self.clear_files1.setStyleSheet("background-color: rgb(13, 101, 195);\n"
"color: rgb(255, 255, 255)")
        self.clear_files1.setIconSize(QtCore.QSize(33, 33))
        self.clear_files1.setObjectName("clear_files1")
        self.color_button = QtWidgets.QPushButton(Form)
        self.color_button.setGeometry(QtCore.QRect(80, 510, 141, 31))
        self.color_button.setStyleSheet("background-color: rgb(13, 101, 195);\n"
"color: rgb(255, 255, 255);")
        self.color_button.setObjectName("color_button")
        self.clear_all = QtWidgets.QPushButton(Form)
        self.clear_all.setGeometry(QtCore.QRect(120, 620, 121, 31))
        self.clear_all.setStyleSheet("background-color: rgb(13, 101, 195);\n"
"color: rgb(255, 255, 255);")
        self.clear_all.setObjectName("clear_all")
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(360, 170, 281, 61))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.box_step3_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.box_step3_3.setContentsMargins(0, 0, 0, 0)
        self.box_step3_3.setObjectName("box_step3_3")
        self.label_fname2_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        self.label_fname2_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 7pt \"MS Shell Dlg 2\";\n"
"")
        self.label_fname2_2.setObjectName("label_fname2_2")
        self.box_step3_3.addWidget(self.label_fname2_2)
        self.input_fname2_2 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.input_fname2_2.sizePolicy().hasHeightForWidth())
        self.input_fname2_2.setSizePolicy(sizePolicy)
        self.input_fname2_2.setStyleSheet("background-color: rgb(208, 208, 208);")
        self.input_fname2_2.setText("")
        self.input_fname2_2.setObjectName("input_fname2_2")
        self.box_step3_3.addWidget(self.input_fname2_2)
        self.save_file2_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save_file2_2.sizePolicy().hasHeightForWidth())
        self.save_file2_2.setSizePolicy(sizePolicy)
        self.save_file2_2.setStyleSheet("background-color: rgb(13, 101, 195);\n"
"color: rgb(255, 255, 255);")
        self.save_file2_2.setObjectName("save_file2_2")
        self.box_step3_3.addWidget(self.save_file2_2)
        self.hs_browse = QtWidgets.QTextBrowser(Form)
        self.hs_browse.setGeometry(QtCore.QRect(380, 330, 181, 101))
        self.hs_browse.setStyleSheet("background-color: rgb(208, 208, 208);\n"
"selection-color: rgb(118, 197, 230);")
        self.hs_browse.setObjectName("hs_browse")
        self.clear_hs = QtWidgets.QPushButton(Form)
        self.clear_hs.setGeometry(QtCore.QRect(580, 380, 51, 41))
        self.clear_hs.setStyleSheet("background-color: rgb(13, 101, 195);\n"
"color: rgb(255, 255, 255)")
        self.clear_hs.setIconSize(QtCore.QSize(33, 30))
        self.clear_hs.setObjectName("clear_hs")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.title.setText(_translate("Form", "PyMOL HotSpots Plugin"))
        self.step3.setText(_translate("Form", "STEP 3:  Color Spectrum"))
        self.browse_button1.setText(_translate("Form", "BROWSE"))
        self.step2.setText(_translate("Form", "STEP 2:  Save All HotSpots"))
        self.step6.setText(_translate("Form", "STEP 6:     Search groups"))
        self.label_fname1.setText(_translate("Form", "FILE NAME"))
        self.save_file1.setText(_translate("Form", "SAVE FILE"))
        self.label_radius1.setText(_translate("Form", "RADIUS     "))
        self.ok1.setText(_translate("Form", "OK"))
        self.label_radius2.setText(_translate("Form", "RADIUS     "))
        self.ok2.setText(_translate("Form", "OK"))
        self.label_fname3.setText(_translate("Form", "FILE NAME"))
        self.save_file3.setText(_translate("Form", "SAVE FILE"))
        self.button_close.setText(_translate("Form", "CLOSE"))
        self.add_hs.setText(_translate("Form", "ADD"))
        self.step1.setText(_translate("Form", "STEP 1:  Select Files"))
        self.step4.setText(_translate("Form", "STEP 4:    HotSpots Simplification"))
        self.step5.setText(_translate("Form", "STEP 5:     Choose HotSpots"))
        self.load1.setText(_translate("Form", "LOAD"))
        self.label.setText(_translate("Form", "        HOTSPOTS"))
        self.label_2.setText(_translate("Form", "        PROTEINS"))
        self.label_3.setText(_translate("Form", "  +"))
        self.clear_files1.setText(_translate("Form", "CLEAR"))
        self.color_button.setText(_translate("Form", "COLOR"))
        self.clear_all.setText(_translate("Form", "CLEAR"))
        self.label_fname2_2.setText(_translate("Form", "FILE NAME"))
        self.save_file2_2.setText(_translate("Form", "SAVE FILE"))
        self.clear_hs.setText(_translate("Form", "CLEAR"))
import inz_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
